spring:
  banner:
    location: banner.txt
  flyway:
    enabled: true
    schemas: clique_res
  jpa:
    database: default
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/cr?ApplicationName=cr-service'
    username: cr
    password: cr
    hikari:
      minimum-idle: 5
      maximum-pool-size: 25
      idle-timeout: 30000

  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: always
server:
  servlet:
    context-path: /api
  port: 8080
