spring.datasource.url=${clique.res.jdbc.url}
spring.datasource.username=${clique.res.jdbc.username}
spring.datasource.password=${clique.res.jdbc.password}


spring.flyway.url = ${clique.res.jdbc.url}
spring.flyway.schemas = public
spring.flyway.user = ${clique.res.jdbc.username}
spring.flyway.password = ${clique.res.jdbc.username}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect